Volunteers/Controllers/BadgesController.cs
using Microsoft.AspNetCore.Mvc;
using Volunteers.Services.Badges;
using Volunteers.Services.Notifications;

namespace Volunteers.Controllers
{
    public class BadgesController : BaseController
    {
        private readonly IBadgesService badges;

        public BadgesController(INotificationsService notifications, IBadgesService badges) : base(notifications)
        {
            this.badges = badges;
        }

        public IActionResult Index()
        {
            return View(badges.GetAllBadges());
        }
    }
}

Volunteers/Controllers/CommentsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Volunteers.Services.Comments;
using static Volunteers.WebConstants;
using Volunteers.Services.Notifications;

namespace Volunteers.Controllers
{
    public class CommentsController : BaseController
    {
        private readonly ICommentService comments;

        public CommentsController(ICommentService comments, INotificationsService notifications) : base(notifications)
        {
            this.comments = comments;
        }

        [Authorize]
        [HttpPost]
        public IActionResult Add(string comment, string Id)
        {
            ViewData["comment"] = comment;

            comments.Add(comment, Id, User.FindFirstValue(ClaimTypes.NameIdentifier));
            TempData[GlobalMessageKey] = PostedComment;
            return Redirect("/Projects/Details/" + $"{Id}");
        }

        
    }
}

Volunteers/Controllers/UsersController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Volunteers.Services.Notifications;
using Volunteers.Services.Users;

namespace Volunteers.Controllers
{
    public class UsersController : BaseController
    {
        private readonly IUserService users;

        public UsersController(INotificationsService notifications, IUserService users) : base(notifications)
        {
            this.users = users;
        }

        public async Task<IActionResult> Profile(string Id)
        {
            if (!await users.IsValid(Id))
            {
                return RedirectToAction("Error", "Home");
            }

            return View(await users.GetUserInfo(Id));
        }

        public async Task<IActionResult> Participants()
        {

            return View(await users.AllUsersInfo());
        }
    }
}

Volunteers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Volunteers</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
          integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
          crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
            integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
            crossorigin=""></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="top-note"><b>Note:</b> this app was developed for educational purposes only. All information you enter is public. Please, don't post any personal information or offensive content.</div>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <div class="logo">
                    <a asp-area="" asp-controller="Home" asp-action="Index"><img style="text-align:center;" src="/pngkey.com-volunteer-icon-png-3346199.png" /></a>
                </div>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Volunteers home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item-add">
                            <a class="nav-link" asp-area="" asp-controller="Projects" asp-action="Create">New project</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="Index">All projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Participants" alt="all users"><i class="fa-solid fa-users"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Badges" asp-action="Index"><i class="fa-solid fa-certificate"></i></a>
                        </li>
                        <li class="nav-item">
                            @if (User.IsInRole("Administrator"))
                            {
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Projects" asp-action="Index"><b>Admin</b></a>
                            }
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @if (TempData.ContainsKey(WebConstants.GlobalMessageKey))
        {
            <div class="alert alert-success text-center" role="alert">
                @TempData[WebConstants.GlobalMessageKey]
            </div>
        }
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-center">
        <section class="footer-icons">
            <a href="https://www.facebook.com/" target="_blank" rel="noreferrer"><i class="fab fa-facebook"></i></a>
            <a href="https://twitter.com/" target="_blank" rel="noreferrer"><i class="fab fa-twitter"></i></a>
            <a href="https://instagram.com/" target="_blank" rel="noreferrer"><i class="fab fa-instagram"></i></a>
            <a href="https://youtube.com/" target="_blank" rel="noreferrer"><i class="fab fa-youtube"></i></a>
        </section>
        <section class="container">
            &copy; 2021 - @DateTime.UtcNow.Year - Volunteers
            <br />
            <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> | 
            <a asp-area="" asp-controller="Home" asp-action="Privacy">Cookies</a> | 
            <a href='https://github.com/damian-ivanov/Volunteers' rel="noreferrer" target="_blank">source code <i class="fab fa-github"></i></a>
        </section>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/notification.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Volunteers/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Volunteers</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" style="background-color: #cccccc !important">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Volunteers home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a style="margin-right: 10px;" type="button" class="btn btn-secondary" asp-area="" asp-controller="Projects" asp-action="Admin">
                                Pending projects: <span class="badge badge-light">@ViewBag.ProjectsCount</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a type="button" class="btn btn-secondary" asp-area="" asp-controller="Comments" asp-action="Admin">
                                Pending comments: <span class="badge badge-light">@ViewBag.CommentsCount</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color: #cccccc !important">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - Volunteers - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>